[package]
name = "tim7775/multi-cache"
description = "https://github.com/tim7775/luau-caching-and-memoization"
version = "0.1.1"
license = "MIT"
authors = ["Tim7775"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
